name: test1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  cloud_firestore: ^5.4.1
  firebase_storage: ^12.3.0
  flutter_local_notifications: ^17.2.2
  cupertino_icons: ^1.0.6
  circular_countdown_timer: ^0.2.4
  contacts_service: ^0.6.3
  permission_handler: ^10.2.0
  flutter_screenutil: ^5.6.0
  device_apps: ^2.2.0
  image_picker: ^1.1.2
  shared_preferences: ^2.0.15
  audioplayers: ^3.0.1
  table_calendar: ^3.0.0
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/bg.png
    - assets/images/image.png
    - assets/images/img.png
    - assets/alarms/alarm_ap4.wav
    - assets/images/work.png

# Add system sound to Android res/raw
android:
  sound: assets/alarms/alarm_ap4.wav